name: FirstLogIn
main: firstlogin.FirstLogin
version: 1.7.1
api-version: '1.20'
author: BooPug Studios
description: First login messages and stats (updated for 1.20.1+)
softdepend:
  - PlaceholderAPI
commands:
  listp:
    description: shows number of ppl on server
    usage: /listp
  pnames:
    description: lists the names of the ppl on the server
    usage: /pnames
  owner:
    description: shows the owner of the server
    usage: /owner
  onlinep:
    description: shows the number of currently online players
    usage: /onlinep
  firsthelp:
    description: shows all the commands.
    usage: /firsthelp
  firstlogin:
    description: Admin commands for FirstLogin
    usage: '/firstlogin <locale <locale|reset>|reload|seen <player>|reset <player|all>|gui <open|accept|trigger>|clearcooldown <player> <key|all>|clearflag <player> <flag|all>>'
    aliases: [fl, flogin]
permissions:
  firstlogin.admin:
    description: Allows use of /firstlogin admin commands
    default: op
  firstlogin.command.listp:
    description: Allows use of /listp
    default: op
  firstlogin.command.pnames:
    description: Allows use of /pnames
    default: op
  firstlogin.command.owner:
    description: Allows use of /owner
    default: op
  firstlogin.command.onlinep:
    description: Allows use of /onlinep
    default: op
  firstlogin.command.firsthelp:
    description: Allows use of /firsthelp
    default: true
