name: FirstLogIn
main: me.bush.firstlogin.FirstLogin
version: 1.4
author: Bush
commands:
  listp:
    Description: shows number of ppl on server
    Usage: /listp
  pnames:
    Description: lists the names of the ppl on the server
    Usage: /pnames
  owner:
    Description: shows the owner of the server
    Usage: /owner    
  onlinep:
    Description: shows the number of currently online players
    Usage: /owner
  firsthelp:
    Description: shows all the commands.
    Usage: /firsthelp